[bar/main]
width = 100%
height = 28
background = #222222
foreground = #ffffff
padding-left = 2
padding-right = 2
module-margin = 2
font-0 = "DejaVu Sans Mono:size=10;2"
font-1 = "Font Awesome 5 Free Solid:size=10;2"
font-2 = "Font Awesome 5 Brands:size=10;2"

modules-left = i3
modules-center = date
modules-right = cpu memory wlan eth pulseaudio battery

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MODULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3
format = <label-state>
wrapping-scroll = false

[module/date]
type = internal/date
interval = 10
date = " %H:%M"
date-alt = " %Y-%m-%d %H:%M"

[module/cpu]
type = internal/cpu
interval = 2
format = "  <total>%"

[module/memory]
type = internal/memory
interval = 5
format = "  <used>/<total>"

[module/pulseaudio]
type = internal/pulseaudio
format-volume = "  <volume>%"
format-muted = "  muted"

[module/wlan]
type = internal/network
interface-type = wireless
format-connected = "  %essid %signal%"
format-disconnected = "睊  off"

[module/eth]
type = internal/network
interface-type = wired
format-connected = ""
format-disconnected = ""

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
format-charging = "  <percentage>%"
format-discharging = "  <percentage>%"
format-full = ""
